name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
          registry-url: 'https://npm.pkg.github.com'

      - name: Configure npm to use GitHub Package Registry
        run: echo "@krishpy3:registry=https://npm.pkg.github.com" > .npmrc

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      
      - name: Print npmrc
        run: cat .npmrc

      - name: Install dependencies
        run: npm install

      - name: Generate changelog and release
        # run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
